#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "/Users/stephanieho/Library/CloudStorage/OneDrive-UBC/Year 4 UBC/CPSC 427/team-16/"
